### ISSUE TITLE
Refactor de modelos

### ISSUE THREAD

**Issue by mgaitan** [OpenDataCordoba/escrutinio-social#41]
Para la elección de Córdoba 2019, con @avdata99 introdujimos [un cambio importante para permitir múltiples "elecciones"](https://github.com/OpenDataCordoba/escrutinio-social/pull/14) (es decir, categorias electivas). 

Hay que continuar ese refactor. 

- [x] Renombrar el modelo `Eleccion` al más semántico `Categoría`
- [x] Agregar un nuevo modelo `Eleccion`, que factorice fecha, lugar y otra metadata de las 
categorias. `Categoria` contendria ahora un foreignkey a todas las elecciones que la contienen. Las mesas siguen relacionadas a las categorias.  Esto permitiria tener multiples elecciones cargadas en el sistema.  
- [x] `VotoMesaReportado` también debe ser separado agregando un objeto contenedor `Carga` que contenga `categoria`, `mesa`, `usuario`, `fecha_hora`, simplificando el modelo actual con un fk `carga`,  `opcion`  y el entero  `votos`.  Podemos evaluar si el flag de "problema" puede ir también en el modelo `Carga`.

**Comment by mgaitan** [comment]
Empiezo esto.

**Comment by cjbarroso** [comment]
Que falta para cerrar esto?

**Comment by mgaitan** [comment]
que llegue usted, compañero
