### ISSUE TITLE
Infraestructura Docker

### ISSUE THREAD

**Issue by mgaitan** [OpenDataCordoba/escrutinio-social#53]
Para facilitar colaboración necesitamos minimizar el esfuerzo de kickoff del proyecto. Tener infraestructura basada en docker / dockercompose que levante el sitio listo para desarrollo (incluyendo datos sintéticos) será muy útil. 

ver trabajo realizado en el proyecto original por @martingalloar
https://github.com/democraciaconcodigos/escrutinio-social/pull/40

**Comment by mgaitan** [comment]
@martingalloar avisá si lo podés encarar en breve sino le metemos y agarrás alguna otra cosa. Es importante para minimizar el esfuerzo de sumarse al proyecto, hay mucha gente que no sabe o le da fiaca armar virtualenv, base de datos y demás. 

ni siquiera hace falta compose, todo en un sólo contenedor está ok para el propósito de "entorno de desarrollo"

**Comment by eamanu** [comment]
@mgaitan Creo que este issue se puede cerrar?
