### ISSUE TITLE
Configurar Travis

### ISSUE THREAD

**Issue by mgaitan** [OpenDataCordoba/escrutinio-social#54]
ya existen algunos tests unitarios y la intención es aumentar la cobertura al 100%. 
Necesitamos integración continua para facilitar la recepción de PRs .

**Comment by eamanu** [comment]
Lo tomo :)

**Comment by eamanu** [comment]
Creo que este Issue se pude cerrar via #60

**Comment by mgaitan** [comment]
gracias @eamanu
